EDUCATION_DISCLAIMER = "Education only; not for clinical use."
SYSTEM_SEARCH = EDUCATION_DISCLAIMER
SYSTEM_FLASHCARDS = EDUCATION_DISCLAIMER
SYSTEM_MCQS = EDUCATION_DISCLAIMER
SYSTEM_OSCE = EDUCATION_DISCLAIMER
SYSTEM_NOTEBOOK = EDUCATION_DISCLAIMER
FLASHCARD_FORMAT = "Return JSON list of {front, back, source}."
MCQ_FORMAT = "Return JSON list of {stem, options, correct_index, explanation, source}."
